name: .NET Build and Test

on:
  push:
    branches: [ main ]

jobs:
  restore:
    runs-on: ubuntu-latest
    name: Restore NuGet Packages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install MAUI workload
        run: dotnet workload install maui-android

      - name: Restore NuGet packages
        run: dotnet restore

  build:
    needs: restore
    runs-on: ubuntu-latest
    name: Build Solution
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install MAUI workload
        run: dotnet workload install maui-android

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

  test:
    needs: build
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # Install Android workload on Ubuntu, since Linux is not officially supported as Desktop
      - name: Install MAUI workload
        run: dotnet workload install maui-android

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal
